LDEV-178 build: support MLNX OFED 2.3
* enhance lbuild to download MLNX automatically
* enhance lbuild to build sles11sp3 with MLNX

Signed-off-by: Minh Diep <minh.diep@intel.com>
Change-Id: I7c69b104eaa1475792390f8e650ce8cf88b78a53
Lustre-change: http://review.whamcloud.com/12511
Lustre-commit: 5177f8186ece11f94df8b499fb9dcccdc42b1944
Reviewed-by: Bob Glossman <bob.glossman@intel.com>
Reviewed-by: Frank Heckes <Frank.Heckes@intel.com>
Reviewed-by: Dmitry Eremin <dmitry.eremin@intel.com>
Reviewed-on: http://review.whamcloud.com/16398
Tested-by: Jenkins
Tested-by: Maloo <hpdd-maloo@intel.com>
Reviewed-by: Oleg Drokin <oleg.drokin@intel.com>

diff --git a/contrib/lbuild/lbuild b/contrib/lbuild/lbuild
--- a/contrib/lbuild/lbuild
+++ b/contrib/lbuild/lbuild
@@ -576,6 +576,20 @@ download_ofed() {
 
 }
 
+download_mlnx() {
+	local force="${1:-false}"
+	local version="${MLNX_VERSION}"
+	local distro_name="${DISTRO}"
+	local arch="${TARGET_ARCH}"
+	local location="http://www.mellanox.com/downloads/ofed/MLNX_OFED-${version}"
+	# this is a work around for suse distro (sles11.3). what we need is
+	# sles11sp3. We really need to redesign how we use target and distro
+	[[ $distro_name =~ sles ]] && distro_name=${DISTRO/./sp}
+	local file="MLNX_OFED_LINUX-${version}-${distro_name}-${arch}.tgz"
+
+	download_file "$location/$file" "$KERNELTREE" "$force"
+}
+
 parse_mpss_info() {
     local file="$1"
     local build="$2"
@@ -811,6 +825,41 @@ untar() {
     echo "Untarring ${tarfile##*/}..."
     tar $(tarflags "$tarfile") "$tarfile" $extractfile
 
+}
+
+unpack_mlnx() {
+	local version="${MLNX_VERSION}"
+	local distro_name="${DISTRO}"
+	local arch="${TARGET_ARCH}"
+
+	# this is a work around for suse distro (sles11.3). what we need is
+	# sles11sp3. We really need to redesign how we use target and distro
+	[[ $distro_name =~ sles ]] && distro_name=${DISTRO/./sp}
+	local mlnx_filename="MLNX_OFED_LINUX-${version}-${distro_name}-${arch}"
+
+	#if a src tarball has been given in the command line, we use it
+	#The format of the directory after untar MUST be in MLNX_OFED_SRC-${version}
+	if [ -n "${OFED_SRC}" ]; then
+		if ! untar "$KERNELTREE/${OFED_SRC}"; then
+			return 1
+		fi
+	else
+	# it's not important what distro we get the tarball since we only
+	# interest in the src
+		if ! untar "$KERNELTREE/${mlnx_filename}.tgz"; then
+			return 1
+		fi
+		# we need to untar again to get the src since it's being
+		# wrapped inside the tarball
+		# There are cases where the source version is different
+		# than the tarball.
+		# (ie. MLNX_OFED_LINUX-2.3-1.0.1 but MLNX_OFED_SRC-2.3-1.0.0)
+		local src=$(ls ${mlnx_filename}/src/MLNX_OFED_SRC-${version%.*}*.tgz)
+		if ! untar "$src"; then
+			return 1
+		fi
+	fi
+	[ -d OFED ] || ln -sf MLNX_OFED_SRC-[0-9].[0-9]* OFED
 }
 
 unpack_ofed() {
@@ -1314,14 +1363,19 @@ build_kernel_ib() {
         K_SRC="KSRC"
     fi
 
-    local OFED_CORE="--with-core-mod --with-ipoib-mod --with-user_mad-mod --with-user_access-mod --with-addr_trans-mod"
-    local OFED_HARDWARE="--with-mthca-mod --with-mlx4-mod --with-mlx4_en-mod --with-cxgb3-mod --with-nes-mod --with-qib-mod"
+	local OFED_CORE="--with-core-mod --with-ipoib-mod --with-user_mad-mod \
+	--with-user_access-mod --with-addr_trans-mod --with-madeye-mod"
+	local OFED_HARDWARE="--with-mthca-mod --with-mlx4-mod \
+	--with-mlx4_en-mod --with-cxgb3-mod --with-mlx4_en-mod \
+	--with-cxgb3-mod --with-nes-mod --with-mlx5-mod --with-cxgb4-mod \
+	--with-qib-mod"
 
-    if compare_version $OFED_VERSION 3.0; then
-	OFED_CORE="$OFED_CORE --with-madeye-mod --with-rds-mod"
-    else
-	OFED_HARDWARE="$OFED_HARDWARE --with-mlx5-mod --with-cxgb4-mod --with-ocrdma-mod --with-qib-mod"
-    fi
+	# Removing the check for older version support
+    #if compare_version $o2ib_version 3.0; then
+    #    OFED_CORE="$OFED_CORE --with-madeye-mod --with-rds-mod"
+    #else
+    #    OFED_HARDWARE="$OFED_HARDWARE --with-cxgb4-mod"
+    #fi
 
     # some I/B drivers are architecture dependent and kernel-ib's configure
     # does not figure it out for us ~sigh~
@@ -1636,6 +1690,7 @@ build_ofed() {
     local ofed_version="$2"
     local kib_prefix
     local kib_rpm
+    local pre_prefix
 
     # if an ofed version is given, then it means use OFED proper,
     # not any vendor specific "inkernel" version
@@ -1658,9 +1713,10 @@ build_ofed() {
         else
             return 0
         fi
-    elif compare_version $OFED_VERSION 3.0; then
-	kib_prefix="ofa_kernel"
-	kib_rpm="kernel-ib"
+    elif compare_version $o2ib_version 3.0; then
+        kib_prefix="ofa_kernel"
+	[ -n "${MLNX_VERSION}" ] && pre_prefix="mlnx-"
+        kib_rpm="kernel-ib"
     else
 	kib_prefix="compat-rdma"
 	kib_rpm="compat-rdma"
@@ -1701,7 +1757,7 @@ build_ofed() {
             create_rpmbuild_dirs
         fi
         # build it
-        build_kernel_ib "${linux}" "${kib_prefix}" "${kib_rpm}"
+        build_kernel_ib "${linux}" "${pre_prefix}${kib_prefix}" "${kib_rpm}" "${o2ib_version}"
 
         if [ -z "$REUSE_SIGNATURE" ]; then
             echo "No reuse signature was caculated so not storing the built ofed"
@@ -1743,7 +1799,9 @@ build_ofed() {
     if ! rpm2cpio < $rpm | cpio -id; then
         fatal 1 "could not unpack the ${kib_rpm}-devel rpm."
     fi
-    CONFIGURE_FLAGS="--with-o2ib=$(pwd)/usr/src/${kib_prefix} ${CONFIGURE_FLAGS}"
+	o2ib_location="$(pwd)/usr/src/${kib_prefix}"
+	[ -n "${MLNX_VERSION}" ] && o2ib_location="${o2ib_location}/default"
+	CONFIGURE_FLAGS="--with-o2ib=${o2ib_location} ${CONFIGURE_FLAGS}"
     popd >/dev/null
 
 }
@@ -2135,6 +2193,13 @@ unpack_lustre
 BUILDID=$(sed -n -e 's/^BUILDID = //p' lustre/META)
 
 load_target
+
+if [ -n "$MLNX_VERSION" ]; then
+    # Don't build OFED at all since it's explicitly built Mellanox
+    OFED_VERSION=""
+	download_mlnx
+    unpack_mlnx || fatal 1 "Error unpacking MLNX tarball"
+fi
 
 if [ -n "$OFED_VERSION" -a "$OFED_VERSION" != "inkernel" ]; then
     download_ofed
