LDEV-110 build: fix linux-obj path for sles
symlink the linux-obj path so OFED can use it

Signed-off-by: Minh Diep <minh.diep@intel.com>
Change-Id: I06468417369e2e97b57ed35f61d5392d8d4cbf6c
Reviewed-on: http://review.whamcloud.com/15797
Reviewed-by: Bob Glossman <bob.glossman@intel.com>
Tested-by: Jenkins
Tested-by: Maloo <hpdd-maloo@intel.com>
Reviewed-by: Dmitry Eremin <dmitry.eremin@intel.com>
Reviewed-by: Oleg Drokin <oleg.drokin@intel.com>

diff --git a/contrib/lbuild/lbuild b/contrib/lbuild/lbuild
--- a/contrib/lbuild/lbuild
+++ b/contrib/lbuild/lbuild
@@ -1511,19 +1511,32 @@ EOF
 	# a place to change/add any unique config
 	case $ofed_type in
 		ofa) local K_SRC_OBJ="K_SRC_OBJ"
-			;;
+		if ! $RPMBUILD $BUILD_TYPE --define 'build_kernel_ib 1' \
+			--define 'build_kernel_ib_devel 1' \
+			${FIND_REQUIRES:+--define "__find_requires $FIND_REQUIRES"} \
+			--define "_topdir ${TOPDIR}" --target ${TARGET_ARCH} \
+			--define "KVERSION ${linuxrelease}" \
+			--define "$K_SRC ${linux}" \
+			${K_SRC_OBJ:+--define "$K_SRC_OBJ ${linux}"} \
+			${OFA_KERNEL_RELEASE:+--define "_release $OFA_KERNEL_RELEASE"} \
+			--define "configure_options --without-quilt $OFED_CORE $OFED_HARDWARE $OFED_ISCSI" \
+			${SOURCE} 2>&1; then
+			fatal 1 "Error building ${kib_rpm}"
+		fi
+		;;
+		mlnx)
+		if ! $RPMBUILD $BUILD_TYPE \
+			${FIND_REQUIRES:+--define "__find_requires $FIND_REQUIRES"} \
+			--define "_topdir ${TOPDIR}" --target ${TARGET_ARCH} \
+			--define "KVERSION ${linuxrelease}" \
+			--define "$K_SRC ${linux}" \
+			${OFA_KERNEL_RELEASE:+--define "_release $OFA_KERNEL_RELEASE"} \
+			--define "configure_options --without-quilt $OFED_CORE $OFED_HARDWARE $OFED_ISCSI" \
+			${SOURCE} 2>&1; then
+			fatal 1 "Error building ${kib_rpm}"
+		fi
+		;;
 	esac
-    if ! $RPMBUILD $BUILD_TYPE --define 'build_kernel_ib 1' --define 'build_kernel_ib_devel 1' \
-                  ${FIND_REQUIRES:+--define "__find_requires $FIND_REQUIRES"} \
-                  --define "_topdir ${TOPDIR}" --target ${TARGET_ARCH} \
-                  --define "KVERSION ${linuxrelease}" \
-                  --define "$K_SRC ${linux}" \
-                  ${K_SRC_OBJ:+--define "$K_SRC_OBJ ${linux}"} \
-                  ${OFA_KERNEL_RELEASE:+--define "_release $OFA_KERNEL_RELEASE"} \
-                  --define "configure_options --without-quilt $OFED_CORE $OFED_HARDWARE $OFED_ISCSI" \
-                  ${SOURCE} 2>&1; then
-        fatal 1 "Error building ${kib_rpm}"
-    fi
 
 }
 
